CREATE TABLE note (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(100) NOT NULL CHECK (LENGTH(title) BETWEEN 3 AND 100),
    context VARCHAR(250) NOT NULL CHECK (LENGTH(context) BETWEEN 3 AND 250)
);